"""add business review summary cache

Revision ID: 041d175358ce
Revises: 31c8e8d9e268
Create Date: 2026-10-09 21:26:40.593722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041d175358ce'
down_revision: Union[str, Sequence[str], None] = '31c8e8d9e268'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_review_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_id', sa.Integer(), nullable=False),
    sa.Column('review_signature', sa.String(length=64), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('overall_sentiment', sa.String(length=30), nullable=False),
    sa.Column('positive_themes', sa.JSON(), nullable=False),
    sa.Column('negative_themes', sa.JSON(), nullable=False),
    sa.Column('recurring_themes', sa.JSON(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['business_id'], ['businesses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_review_summaries_business_id'), 'business_review_summaries', ['business_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_review_summaries_business_id'), table_name='business_review_summaries')
    op.drop_table('business_review_summaries')
    # ### end Alembic commands ###
